dist: trusty
language: python
python:
  - "2.7"

install:
  - sudo apt-get install python3 python-dbus-dev python-dbus libdbus-1-dev libdbus-glib-1-dev
  - pip3 install coala-bears
  - pip install notify2
  - pip install dbus-python
  - ./setup.sh
  - cd $TRAVIS_BUILD_DIR

script:
  - coala --ci
  - cd jarviscli/
  - python -m unittest discover
