dist: trusty
language: python
python:
  - "2.7"

install:
  - sudo apt-get install python3
  - pip install -r requirements.txt
  - pip3 install coala-bears
  - cd $TRAVIS_BUILD_DIR

script:
  - coala --ci
  - cd jarviscli/
  - python -m unittest discover
